const N={K:'王',R:'飛',B:'角',G:'金',S:'銀',N:'桂',L:'香',P:'歩'},PN={R:'竜',B:'馬',S:'全',N:'圭',L:'杏',P:'と'},V={K:500,R:10,B:9,G:6,S:5,N:3,L:3,P:1};
const SPRITE={P:'s00',L:'s01',N:'s02',S:'s03',G:'s10',B:'s11',R:'s12',K:'s13','+P':'s20','+L':'s21','+N':'s22','+S':'s23','+B':'s30','+R':'s31'};
const LEVELS={beginner:{name:'初心者',depth:1,beam:30,root:40,time:350},intermediate:{name:'中級者',depth:3,beam:8,root:24,time:900},advanced:{name:'上級者',depth:5,beam:5,root:16,time:1700},master:{name:'猛者',depth:7,beam:3,root:12,time:2800}};
const boardEl=$('#board'),statusEl=$('#status'),thinkingEl=$('#thinking'),promotion=$('#promotion');
const dirs={K:[[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0],[1,1]],G:[[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,0]],S:[[-1,-1],[-1,0],[-1,1],[1,-1],[1,1]],N:[[-2,-1],[-2,1]],P:[[-1,0]]};
const goldLike=new Set(['G','S','N','L','P']);
let state,selected=null,legalTargets=[],history=[],busy=false,level='intermediate',searchNodes=0;
function $(s){return document.querySelector(s)}
function fresh(){const rows=[['L','N','S','G','K','G','S','N','L'],[null,'R',null,null,null,null,null,'B',null],['P','P','P','P','P','P','P','P','P'],...Array.from({length:3},()=>Array(9).fill(null)),['P','P','P','P','P','P','P','P','P'],[null,'B',null,null,null,null,null,'R',null],['L','N','S','G','K','G','S','N','L']];return{board:rows.map((row,r)=>row.map(type=>type?{type,side:r<3?'gote':'sente',promoted:false}:null)),hands:{sente:[],gote:[]},turn:'sente',last:null,winner:null,move:0}}
function clone(s){return{board:s.board.map(row=>row.map(p=>p&&{...p})),hands:{sente:[...s.hands.sente],gote:[...s.hands.gote]},turn:s.turn,last:s.last&&{from:s.last.from&&[...s.last.from],to:[...s.last.to]},winner:s.winner,move:s.move}}
function inside(r,c){return r>=0&&r<9&&c>=0&&c<9}function other(s){return s==='sente'?'gote':'sente'}function orient(side,d){return side==='sente'?d:[-d[0],-d[1]]}
function pseudoMoves(s,r,c,attackOnly=false){const p=s.board[r][c];if(!p)return[];const out=[],add=(rr,cc)=>{if(!inside(rr,cc))return false;const q=s.board[rr][cc];if(!q||q.side!==p.side)out.push([rr,cc]);return !q};let steps;
  if(p.promoted&&goldLike.has(p.type))steps=dirs.G;else if(p.type==='K')steps=dirs.K;else if(p.type==='G')steps=dirs.G;else if(p.type==='S')steps=dirs.S;else if(p.type==='N')steps=dirs.N;else if(p.type==='P')steps=dirs.P;
  if(steps)for(const d of steps){const [dr,dc]=orient(p.side,d);add(r+dr,c+dc)}
  if(p.promoted&&p.type==='B')for(const [dr,dc] of [[-1,0],[1,0],[0,-1],[0,1]])add(r+dr,c+dc);
  if(p.promoted&&p.type==='R')for(const [dr,dc] of [[-1,-1],[-1,1],[1,-1],[1,1]])add(r+dr,c+dc);
  const slide=[];if(p.type==='R')slide.push([-1,0],[1,0],[0,-1],[0,1]);if(p.type==='B')slide.push([-1,-1],[-1,1],[1,-1],[1,1]);if(p.type==='L'&&!p.promoted)slide.push(orient(p.side,[-1,0]));
  for(const [dr,dc] of slide)for(let n=1;n<9;n++)if(!add(r+dr*n,c+dc*n))break;return out}
function attacked(s,r,c,by){for(let rr=0;rr<9;rr++)for(let cc=0;cc<9;cc++){const p=s.board[rr][cc];if(p?.side===by&&pseudoMoves(s,rr,cc,true).some(x=>x[0]===r&&x[1]===c))return true}return false}
function inCheck(s,side){for(let r=0;r<9;r++)for(let c=0;c<9;c++)if(s.board[r][c]?.side===side&&s.board[r][c].type==='K')return attacked(s,r,c,other(side));return true}
function promotionPossible(p,fr,tr){if(p.type==='K'||p.type==='G'||p.promoted)return false;return p.side==='sente'?(fr<=2||tr<=2):(fr>=6||tr>=6)}
function forcedPromotion(p,tr){return(p.type==='P'||p.type==='L')&&(p.side==='sente'?tr===0:tr===8)||p.type==='N'&&(p.side==='sente'?tr<=1:tr>=7)}
function apply(s,m){const n=clone(s);if(m.drop){const i=n.hands[m.side].indexOf(m.type);if(i<0)return n;n.hands[m.side].splice(i,1);n.board[m.to[0]][m.to[1]]={type:m.type,side:m.side,promoted:false}}else{const p=n.board[m.from[0]][m.from[1]],cap=n.board[m.to[0]][m.to[1]];n.board[m.from[0]][m.from[1]]=null;if(cap)n.hands[m.side].push(cap.type);n.board[m.to[0]][m.to[1]]={...p,promoted:p.promoted||m.promote}}n.last={from:m.from||null,to:m.to};n.turn=other(m.side);n.move++;return n}
function rawMoves(s,side){const out=[];for(let r=0;r<9;r++)for(let c=0;c<9;c++){const p=s.board[r][c];if(p?.side!==side)continue;for(const to of pseudoMoves(s,r,c)){const pp=promotionPossible(p,r,to[0]),forced=forcedPromotion(p,to[0]);out.push({side,from:[r,c],to,promote:forced});if(pp&&!forced)out.push({side,from:[r,c],to,promote:true})}}
  for(const type of new Set(s.hands[side]))for(let r=0;r<9;r++)for(let c=0;c<9;c++){if(s.board[r][c])continue;if((type==='P'||type==='L')&&(side==='sente'?r===0:r===8))continue;if(type==='N'&&(side==='sente'?r<=1:r>=7))continue;if(type==='P'&&s.board.some(row=>row[c]?.side===side&&row[c].type==='P'&&!row[c].promoted))continue;out.push({side,drop:true,type,to:[r,c]})}return out}
function legalMoves(s,side=s.turn){return rawMoves(s,side).filter(m=>!inCheck(apply(s,m),side))}
function key(m){return`${m.drop?'D'+m.type:m.from.join('')}-${m.to.join('')}-${m.promote?1:0}`}
function material(s,side){let sum=0;for(const row of s.board)for(const p of row)if(p)sum+=(p.side===side?1:-1)*(V[p.type]+(p.promoted?2:0));for(const x of s.hands[side])sum+=V[x];for(const x of s.hands[other(side)])sum-=V[x];return sum}
function dangerLoss(s,side){let loss=0;for(let r=0;r<9;r++)for(let c=0;c<9;c++){const p=s.board[r][c];if(p?.side===side&&p.type!=='K'&&attacked(s,r,c,other(side)))loss+=V[p.type]+(p.promoted?2:0)}return loss}
function positional(s,side){let x=0;for(let r=0;r<9;r++)for(let c=0;c<9;c++){const p=s.board[r][c];if(p?.side!==side)continue;x+=(4-Math.abs(4-c))*.12;if(p.type!=='K')x+=(side==='gote'?r:8-r)*.05}return x}
function evaluateMove(s,m){const beforeDanger=dangerLoss(s,m.side),cap=s.board[m.to[0]][m.to[1]],n=apply(s,m),afterDanger=dangerLoss(n,m.side);let score=material(n,m.side)*20+positional(n,m.side)+Math.random()*.8;score+=(beforeDanger-afterDanger)*95;if(cap)score+=V[cap.type]*125;if(m.promote)score+=(V[s.board[m.from[0]][m.from[1]].type]||1)*16;if(attacked(n,m.to[0],m.to[1],other(m.side))){const own=n.board[m.to[0]][m.to[1]];score-=V[own.type]*105}if(inCheck(n,other(m.side)))score+=32;return score}
function staticEval(s,root='gote'){const foe=other(root);let score=material(s,root)*24+positional(s,root)-positional(s,foe);score-=dangerLoss(s,root)*68;score+=dangerLoss(s,foe)*54;if(inCheck(s,foe))score+=28;if(inCheck(s,root))score-=36;return score}
function ordered(s,side,root,limit){const moves=legalMoves(s,side),sign=side===root?1:-1;moves.sort((a,b)=>sign*(staticEval(apply(s,b),root)-staticEval(apply(s,a),root)));return moves.slice(0,limit)}
function minimax(s,depth,alpha,beta,root,beam,deadline){searchNodes++;if(depth<=0||performance.now()>=deadline)return staticEval(s,root);const moves=ordered(s,s.turn,root,beam);if(!moves.length)return inCheck(s,s.turn)?(s.turn===root?-100000-depth:100000+depth):0;if(s.turn===root){let value=-Infinity;for(const m of moves){value=Math.max(value,minimax(apply(s,m),depth-1,alpha,beta,root,beam,deadline));alpha=Math.max(alpha,value);if(beta<=alpha||performance.now()>=deadline)break}return value}let value=Infinity;for(const m of moves){value=Math.min(value,minimax(apply(s,m),depth-1,alpha,beta,root,beam,deadline));beta=Math.min(beta,value);if(beta<=alpha||performance.now()>=deadline)break}return value}
function chooseAI(s){const cfg=LEVELS[level],deadline=performance.now()+cfg.time;searchNodes=0;const moves=legalMoves(s,'gote').sort((a,b)=>evaluateMove(s,b)-evaluateMove(s,a)).slice(0,cfg.root);if(!moves.length)return null;let best=moves[0],bestScore=-Infinity;for(const m of moves){const n=apply(s,m),score=cfg.depth===1?evaluateMove(s,m):minimax(n,cfg.depth-1,-Infinity,Infinity,'gote',cfg.beam,deadline)+evaluateMove(s,m)*.18;if(score>bestScore){bestScore=score;best=m}if(performance.now()>=deadline&&searchNodes>0)break}return best}
function textPiece(p){return p.promoted?(PN[p.type]||N[p.type]):N[p.type]}
function render(){boardEl.replaceChildren();const targets=new Map(legalTargets.map(m=>[m.to.join(','),m]));state.board.forEach((row,r)=>row.forEach((p,c)=>{const b=document.createElement('button'),k=`${r},${c}`,target=targets.get(k);b.className='square';if(selected?.kind==='board'&&selected.r===r&&selected.c===c)b.classList.add('selected');if(target)b.classList.add(p?'capture':'legal');if(state.last&&(state.last.to.join(',')===k||state.last.from?.join(',')===k))b.classList.add('last');b.dataset.r=r;b.dataset.c=c;b.setAttribute('role','gridcell');b.setAttribute('aria-label',`${9-c}筋${r+1}段${p?(p.side==='sente'?'先手':'後手')+textPiece(p):'空き'}`);if(p){const span=document.createElement('span'),code=(p.promoted?'+':'')+p.type;span.className=`piece ${p.side}${p.promoted?' promoted':''}`;span.innerHTML=`<i class="character ${SPRITE[code]||SPRITE[p.type]}"></i><b class="piece-label">${textPiece(p)}</b>`;b.append(span)}b.addEventListener('click',onSquare);boardEl.append(b)}));renderHand('sente');renderHand('gote');statusEl.textContent=state.winner?(state.winner==='sente'?'あなたの勝ちです':'コンピューターの勝ちです'):(state.turn==='sente'?(inCheck(state,'sente')?'王手です。王手を回避してください':'あなたの手番です'):'コンピューターが考えています')}
function renderHand(side){const el=$(`#${side}-hand`);el.replaceChildren();const counts={};state.hands[side].forEach(x=>counts[x]=(counts[x]||0)+1);for(const type of Object.keys(counts).sort((a,b)=>V[b]-V[a])){const b=document.createElement('button');b.className='hand-piece';if(selected?.kind==='hand'&&selected.type===type&&side==='sente')b.classList.add('selected');b.innerHTML=`<i class="hand-character character ${SPRITE[type]}"></i><span>${N[type]}<small class="count">×${counts[type]}</small></span>`;b.disabled=side!=='sente'||state.turn!=='sente'||busy;b.addEventListener('click',()=>selectHand(type));el.append(b)}}
function selectHand(type){if(busy||state.turn!=='sente')return;selected={kind:'hand',type};legalTargets=legalMoves(state,'sente').filter(m=>m.drop&&m.type===type);render()}
function onSquare(e){if(busy||state.turn!=='sente'||state.winner)return;const r=+e.currentTarget.dataset.r,c=+e.currentTarget.dataset.c,match=legalTargets.filter(m=>m.to[0]===r&&m.to[1]===c);if(match.length){commitHuman(match);return}const p=state.board[r][c];if(p?.side==='sente'){selected={kind:'board',r,c};legalTargets=legalMoves(state,'sente').filter(m=>!m.drop&&m.from[0]===r&&m.from[1]===c);render()}else{selected=null;legalTargets=[];render()}}
async function commitHuman(options){let m=options.find(x=>!x.promote)||options[0];if(options.some(x=>x.promote)&&options.some(x=>!x.promote)){promotion.showModal();const answer=await new Promise(resolve=>promotion.addEventListener('close',()=>resolve(promotion.returnValue),{once:true}));m=options.find(x=>x.promote===(answer==='promote'))||m}history.push(clone(state));state=apply(state,m);selected=null;legalTargets=[];finishOrAI()}
function detectEnd(){const moves=legalMoves(state,state.turn);if(!moves.length){state.winner=other(state.turn);return true}return false}
async function finishOrAI(){render();if(detectEnd()){render();return}if(state.turn==='gote'){busy=true;const cfg=LEVELS[level];thinkingEl.textContent=`${cfg.name}・${cfg.depth}手読みで思考中…`;render();await new Promise(r=>setTimeout(r,60));const start=performance.now(),m=chooseAI(state),elapsed=Math.round(performance.now()-start);if(m){history.push(clone(state));state=apply(state,m)}thinkingEl.textContent=`${cfg.name}：${elapsed}ms・${searchNodes.toLocaleString()}局面`;busy=false;if(detectEnd())render();else render()}}
function reset(){state=fresh();selected=null;legalTargets=[];history=[];busy=false;thinkingEl.textContent='';render()}
function setLevel(next){if(busy||!LEVELS[next])return;level=next;document.querySelectorAll('[data-level]').forEach(b=>b.classList.toggle('active',b.dataset.level===level));thinkingEl.textContent=`${LEVELS[level].name}：${LEVELS[level].depth}手先まで読む設定`}
$('#new-game').addEventListener('click',reset);$('#undo').addEventListener('click',()=>{if(busy||!history.length)return;while(history.length){state=history.pop();if(state.turn==='sente')break}selected=null;legalTargets=[];render()});document.querySelectorAll('[data-level]').forEach(b=>b.addEventListener('click',()=>setLevel(b.dataset.level)));reset();setLevel(level);
document.addEventListener('touchmove',e=>{if(e.touches?.length>1)e.preventDefault()},{passive:false});document.addEventListener('gesturestart',e=>e.preventDefault(),{passive:false});document.addEventListener('gesturechange',e=>e.preventDefault(),{passive:false});
